name: Release NVDA Add-on

on:
  push:
    tags: ['v*.*.*']

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y gettext
          pip install scons markdown

      - name: Append Changelog to Readme
        run: |
          echo "" >> readme.md
          echo "## Changelog" >> readme.md
          cat changelog.md >> readme.md

      - name: Build Add-on and Pot file
        run: scons && scons pot

      - name: Extract Changelog
        id: extract_changelog
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          if [ -f "changelog.md" ]; then
            sed -n "/^## $VERSION/,/^## /p" changelog.md | sed '1d;$d' > release_notes.md
          fi
          if [ ! -s release_notes.md ]; then
            echo "Release for version $VERSION" > release_notes.md
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release_notes.md
          files: |
            *.nvda-addon
            *.pot
          draft: false
          prerelease: false
